{:ok, contents} = File.read("puzzleinput5.txt")
filterContents = String.split(contents, "\n", trim: false)
blankline = Enum.find_index(filterContents, fn x-> x == "" end)
idranges = Enum.take(filterContents, blankline)
ids = Enum.map(Enum.slice(filterContents, blankline+1..length(filterContents)), fn x -> String.to_integer(x) end)
idranges = Enum.map(idranges, fn x -> y = to_string(x) 
[a, b] = (String.split(y, "-", trim: true))
{String.to_integer(a), String.to_integer(b)} end)
checks = Enum.filter(ids, fn x -> Enum.any?(idranges, fn y -> x >= elem(y,0) and x <= elem(y,1) end) end)
IO.inspect(Enum.count(checks))
